### ISSUE TITLE
Applying effect to hue makes all pixels turn red

### ISSUE THREAD

**Issue by SixBeeps** [LaineZ/VSTImage#1]
(FYI, am running version 1.2.0.0)
For example, here are two of the same image after applying chorus to the value, then the hue. Hue clearly shouldn't be completely red throughout the whole image, but it appears that way.
![i2](https://user-images.githubusercontent.com/19637928/155265091-c95742db-91df-44b1-80ff-c3a955a32d16.PNG)
![i1](https://user-images.githubusercontent.com/19637928/155265093-87a374cc-31de-4d3c-8bc5-860476d56fa5.PNG)

**Comment by LaineZ** [comment]
Hello @SixBeeps,

I fixed this bug in 1.2.2.0 version. Let me know if this version works for you.

**Comment by SixBeeps** [comment]
> Hello @SixBeeps,
> 
> I fixed this bug in 1.2.2.0 version. Let me know if this version works for you.

The fix worked 👍
